### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by aftm1614** [DroidX-UI-Devices/vendor_droidxOTA#28]
### Device you want to apply for

Redmi Note 12 (Topaz/Tapas)

### Device Tree Sources

https://github.com/aftm1614/android_device_xiaomi_topaz
https://github.com/aftm1614/android_device_xiaomi_topaz-kernel
https://github.com/aftm1614/android_vendor_xiaomi_topaz

### Number of ROM's you maintain officially

None at the moment

### Any Exceptions/special concern?

NA

### Telegram username

@skwel24

### GitHub username

aftm1614

**Comment by hipexscape** [comment]
Hey there skwel,

After proper review, we couldn't find any significant contributions you made to the device which ensures whether you can fix any potential issues that arise.
We couldn't see much of what we would consider a reasonable knowledge after going through the changes you've done.

Try applying later again.

Your regards,
DroidX-UI Team
