### ISSUE TITLE
New maintainer for Redmi Note 11 Pro+ 5G /POCO X4 Pro 5G  (veux/peux)

### ISSUE THREAD

**Issue by Snowman2409** [DroidX-UI-Devices/vendor_droidxOTA#40]
### Device you want to apply for

 Redmi Note 11 Pro+ 5G /POCO X4 Pro 5G  (veux/peux)

### Device Tree Sources

Device tree 
https://github.com/Snowman2409/device_xiaomi_veux.git
Vendor tree
https://github.com/Snowman2409/vendor_xiaomi_veux.git

### Number of ROM's you maintain officially

1 (crDroid)

### Any Exceptions/special concern?

No

### Telegram username

Bad_Snowman

### GitHub username

Snowman2409

**Comment by ashwani212** [comment]
Accepted (Process Completed on TG)

**Comment by beingashwani** [comment]
Accepted (Process Completed on TG)
