### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by onesmiledx** [DroidX-UI-Devices/vendor_droidxOTA#47]
### Device you want to apply for

Samsung Galaxy A71 4G

### Device Tree Sources

https://github.com/onesmiledx/android_device_samsung_a71
https://github.com/onesmiledx/android_device_samsung_a71-common
https://github.com/LineageOS/android_kernel_samsung_a71
https://github.com/TheMuppets/proprietary_vendor_samsung_a71
https://github.com/TheMuppets/proprietary_vendor_samsung_a71-common

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

VoLTE

### Telegram username

@whystarlix

### GitHub username

onesmiledx

**Comment by hipexscape** [comment]
Hey there onesmiledx,

After proper review, we couldn't find any significant contributions you made to the device which ensures whether you can fix any potential issues that arise.
We couldn't see much of what we would consider a reasonable knowledge after going through the changes you've done.

Try applying later again.

Your regards,
DroidX-UI Team
