### ISSUE TITLE
New maintainer for Realme 7/Narzo 20 Pro/ Narzo 30 4g (salaa)

### ISSUE THREAD

**Issue by ShitijHalder** [DroidX-UI-Devices/vendor_droidxOTA#5]
### Device you want to apply for

Realme 7/Narzo 20 Pro/ Narzo 30 4g (salaa)

### Device Tree Sources

Device Tree: https://github.com/ShitijHalder/device_realme_salaa
Vendor Tree: https://github.com/ShitijHalder/vendor_realme_salaa
Kernel Tree: https://github.com/ShitijHalder/kernel_realme_salaa

### Number of ROM's you maintain officially

i am not maintaining any rom officially but i do two unofficially, DerpfestOS and Project Blaze

### Any Exceptions/special concern?

i started building for this device since 1-2 months ago and i am still learning git and other things properly so there can be some minor mistakes but i am determined to build for this device, here is my unofficial build for DroidX UI - https://t.me/shitijposts/352

### Telegram username

@shitijnotop

### GitHub username

ShitijHalder

**Comment by ZirgomHaidar** [comment]
Need to get more experienced at handling DT, KT and VT.

**Comment by hipexscape** [comment]
Hey there ShitijHalder,

After proper review, we couldn't find any significant contributions you made to the device which ensures whether you can fix any potential issues that arise.
We couldn't see much of what we would consider a reasonable knowledge after going through the changes you've done.

Try applying later again.

Your regards,
DroidX-UI Team
